### ISSUE TITLE
Math range error in decision function for large v-values

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#52]
If v-values gets too big, the decision function will fail with math range error.

How to reproduce:
```
n_subjects        : 100
mechanism         : GA
behaviors         : cr,ignore
stimulus_elements : us,cs,none
start_v           : cs->ignore: 0, default: -1
alpha_v           : cs->ignore: 0.0, default: 0.2
beta              : 1
behavior_cost     : cr:1, default: 0
u                 : us:4, default: 0

@variables p_none:0, stop_condition:300


@phase Pavlovian_cond100  stop:cs=stop_condition
START            | NONE(p_none) | CS
CS    cs         | US
US    us            | START
NONE  none       | START

@phase Pavlovian_cond75(Pavlovian_cond100)  stop:cs=stop_condition
CS    cs         | US(0.75)  | NONE

@phase Pavlovian_cond50(Pavlovian_cond100)  stop:cs=stop_condition
CS    cs         | US(0.5)   | NONE

@phase Pavlovian_cond25(Pavlovian_cond100)  stop:cs=stop_condition
CS    cs         | US(0.25)  | NONE

@phase Pavlovian_cond0(Pavlovian_cond100)  stop:cs=stop_condition
CS    cs         |  NONE




@run Pavlovian_cond100 runlabel: p100
@run Pavlovian_cond75 runlabel: p75
@run Pavlovian_cond50 runlabel: p50
@run Pavlovian_cond25 runlabel: p25
@run Pavlovian_cond0 runlabel: p0


xscale: cs
@figure Test of contingency theory for Pavlovian conditioning
#@subplot 221 - {'xlabel':'Trial','ylabel':'Probability', 
'title':'Probability of CR  (thick line is average)'  }
subject: average
runlabel:  p100
@pplot cs->cr {'linewidth':3,'label':'p(US|CS)=1'}
runlabel:  p75
@pplot cs->cr {'linewidth':3,'label':'p(US|CS)=0.75'}
runlabel:  p50
@pplot cs->cr {'linewidth':3,'label':'p(US|CS)=0.50'}
runlabel:  p25
@pplot cs->cr {'linewidth':3,'label':'p(US|CS)=0.25'}
runlabel:  p0
@pplot cs->cr {'linewidth':3,'label':'p(US|CS)=0.0'}
@legend
```

**Comment by drghirlanda** [comment]
@markusrobertjonsson this most likely comes from `exp`, which overflows easily with a large argument. You can work around this by first calculating relative probabilities. Let `v(s->bk)` be the largest `v` of all the `v(s->bi)` we have. You can then calculate:

    p(s -> bi) / p(s -> bk) = exp( beta*( v(s->bi) - v(s->bk ) ) )

these numbers will range between 1 (for `i==k`) and 0. You can then add them all to obtain the normalization factor to transform them into actual probabilities. In fact, the sum of all relative probabilities is `S = sum(i) p(s->bi) / p(s->bk)` and you can see that a relative probability divided by `S` is the same as the probability we want.

Computationally, this is probably not significantly more expensive. We do have to find the max v first and then perform the subtractions. However, because we can set the relative probability of the max v to 1 directly, there are n-1 rather than n subtractions and, more importantly, we save 1 exponentiation. Also, all `exp` will be calculated with smaller arguments, which will give a savings if the `exp` implementation is smart. Summing and normalizing are the same as with the current algorithm.

**Comment by markusrobertjonsson** [comment]
Fixed on issue branch 92. Merged to master.
