### ISSUE TITLE
Should we introduce a new parameter mu to model genetic predisposition?

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#68]
In issue #11 , beta is allowed to take different values for different S->B pairs. This works as intended as long as the v-values are nonnegative, but when they are negative, a high beta-value (for S->B) will decrease the weight for S->B in the decision function, not increase it.
    
One suggestion is to revert #11 (and thereby only allowing scalar beta), and introduce a new parameter (gamma) indexed by S->B pairs, and multiply exp(beta v(S->B)) with gamma(S->B) in the decision function. With two behaviors B1, B2:
    
Pr(S->B1) = gamma(S->B1) exp(beta v(S->B1)) / [ gamma(S->B1) exp(beta v(S->B1)) + gamma(S->B2) exp(beta v(S->B2)) ].

Tasks:
- [x] Keep #11 
- [x] Introduce new parameter according to comments

**Comment by drghirlanda** [comment]
@markusrobertjonsson I see your point. What would gamma be, though? An additive value? That would work, but we could also provide both mechanisms because we still don't know from a scientific point of view which one makes sense. Essentially, we would provide an arbitrary linear transformation of value that is potentially specific for each S->R pair.

I think we should use something different than gamma, though, because gamma is used in machine learning for the discount factor, which is also a feature under consideration.

**Comment by markusrobertjonsson** [comment]
@drghirlanda The new parameter (let's call it gamma for now) would be indexed by S->B pairs. Magnus' suggestion is multiplying exp(beta v(S->B)) with gamma(S->B). With two behaviors B1, B2:
    
Pr(S->B1) = gamma(S->B1) exp(beta v(S->B1))  /  [ gamma(S->B1) exp(beta v(S->B1)) + gamma(S->B2) exp(beta v(S->B2)) ]. 
    
What do you think?

**Comment by drghirlanda** [comment]
That looks equivalent to my suggestion, because (omitting the S->R stuff)

    gamma * exp( beta * v ) = exp( beta * v + log(gamma) )

So it's just a change in the scale of the parameter. I prefer my formulation because it keeps the new parameter in the realm of "value," that is the genetic predisposition can "add value" to (or subtract value from)  to specific behaviors.

I would still like to have the opportuinity to have beta(S->R), though. In fact, my preferred formulation would probably be:

    exp( beta(S->R) *  v(S->R) + gamma(S->R) )

So that gamma acts as a beta-independent value offset but the effect of beta is value-dependent. As I mentioned, we don't know what is the best model of animal decision making, so I think it's good to have both options.

**Comment by markusrobertjonsson** [comment]
@drghirlanda Thanks! Having gamma in the exponent is better. I talked to Magnus about it, and he agrees.

        exp( beta(S->R) *  v(S->R) + gamma(S->R) )

- Should we allow negative gammas?
- Magnus thinks that it suffices to let beta be indexed by stimulus elements (not stimulus element-behaviour pairs). What do you think?

**Comment by drghirlanda** [comment]
@markusrobertjonsson Difficult questions. I guess negative gamma can model inhibition of a response so it could be useful. Regarding beta, if we only have beta(S) we would facilitate all responses without exception when S is presented. Because S is the same for all R being considered, I don't think it makes sense, right? That is, beta(S) would vary across stimulus situations but it would affect all responses equally and thus not favor one R over another. One of our ideas was to use beta to model the fact that some responses may be facilitated over others. I would say to keep the S->R parametrization of beta. If we implement the S->* mechanism, it will be easy to effectively have a beta(S). Again, because we are not sure about what is realistic here, I would not limit our possibilities.

Ideally, beta would be a dynamical variable potentially influenced by the history, but we will wait with this :)

**Comment by markusrobertjonsson** [comment]
@drghirlanda Sounds good! Lastly, do you have a suggestion for name (instead of gamma)? mu, perhaps?

**Comment by drghirlanda** [comment]
@markusrobertjonsson I think mu is free!

**Comment by markusrobertjonsson** [comment]
mu is implemented.
